# Generated by Django 3.1.7 on 2021-09-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbook', '0002_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='today_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
