# Generated by Django 3.1.7 on 2021-09-30 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankbook', '0003_auto_20210929_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='today_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2021, 9, 30)),
        ),
    ]
